url = 'https://id.atlassian.com/login'
email = 'efio.at.work@gmail.com'
username = 'efio at_work'
password = 'aX7&oMCc1^'
token = 'ATBBFd7dbcQNVMRUKPWaxUVuJ4tVC845ACC1'
new_proj_name = 'test_proj_01'
new_proj_key = 'PRJ'
new_repo_name = 'test_repo_01'
branch_name = 'test_branch_01'
filename = 'README.md'
cfg_tests_dir = 'src.cfg.cfg_tests'
REPOSITORY = 'Repository'
PROJECT = 'Project'
REPOSITORIES = 'Repositories'
PROJECTS = 'Projects'


