url = 'https://id.atlassian.com/login'
email = 'efio.at.work@gmail.com'
username = 'efio at_work'
password = ''
new_proj_name = 'test_proj_01'
new_proj_key = 'PRJ'
new_repo_name = 'test_repo_01'
branch_name = 'test_branch_01'
filename = 'README.md'
cfg_tests_dir = 'src.cfg.cfg_tests'
REPOSITORY = 'Repository'
PROJECT = 'Project'
REPOSITORIES = 'Repositories'
PROJECTS = 'Projects'


